### PR TITLE
0.05 Adding configuration while invoking the module.

### PR DESCRIPTION
**Pull request by hjardines**
Hi All.

I encountered an issue where using multiple serializers (XML, JSON, etc) for the same Dancer2 application using the "send_as" method (Ref: https://metacpan.org/pod/distribution/Dancer2/lib/Dancer2/Manual.pod#send_as).

The issue itself is that the configuration is not passed automatically with the current implementation of the Dancer2::Serializer::XML. 

Fix came reviewing https://github.com/PerlDancer/Dancer2/issues/1302.

For this to be automatically loaded the configuration needs to be something like:

```
engines:
   serializer:
      XML:
        serialize:
           RootName: 'SOAP-ENV:Envelope'
           KeyAttr: []
        deserialize:
          KeepRoot: 1
```

Hope it helps.
Harold

### CODE REVIEW

**Comment by realflash** [comment]
Thanks very much! I'll look to pull this in soon.

**Comment by hjardines** [comment]
Thanks, please let me know if you need further assistance.

**Comment by hjardines** [comment]
Just following up on this...

**Comment by realflash** [comment]
Added failing test

**Comment by realflash** [comment]
The test still fails; need more time to work out whether my test is bad. Off on holiday for ten days, so I might finally get chance to look at it later this week.

**Comment by realflash** [comment]
Test is now fixed and passing with a slight tweak to your suggestion to allow options for both serialize() and deserialize() functions. This process has allowed me to figure how engine options should properly be set so I'm going to make some related changes before releasing 0.05. Thanks for your contribution!

**Pull request merged**
